chore: apply shell and YAML linting, fix minor issues
- Reformat bashrc and scripts/install-deps.sh for consistent indentation,
  quoting, and style (shellcheck, shfmt).
- Add .pre-commit-config.yaml for pre-commit hooks (YAML, shellcheck, etc).
- Fix minor typos and whitespace in markdown and config files.
- Remove empty inputrc file.
- Add shebang to direnvrc.
- Improve error handling in bashrc gitignore.io function.
- Fix quoting and variable usage in direnv/lib scripts.
- Use $HOME instead of hardcoded paths for portability.
- No functional changes; improves maintainability and consistency.

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -5,16 +5,16 @@
 # shellcheck disable=SC1090
 # Source global definitions
 if [ -f /etc/bashrc ]; then
-  . /etc/bashrc
+	. /etc/bashrc
 fi
 
 # User specific aliases and functions
 if [ -d ~/.bashrc.d ]; then
-  for rc in ~/.bashrc.d/*; do
-    if [ -f "$rc" ]; then
-      . "$rc"
-    fi
-  done
+	for rc in ~/.bashrc.d/*; do
+		if [ -f "$rc" ]; then
+			. "$rc"
+		fi
+	done
 fi
 
 unset rc
@@ -22,29 +22,25 @@ unset rc
 export XDG_CONFIG_HOME=$HOME/.config
 
 if [ -f "/opt/homebrew/bin/brew" ]; then
-  # We're on Mac :shrug:
-  export BASH_SILENCE_DEPRECATION_WARNING=1
-  eval "$(/opt/homebrew/bin/brew shellenv)"
+	# We're on Mac :shrug:
+	export BASH_SILENCE_DEPRECATION_WARNING=1
+	eval "$(/opt/homebrew/bin/brew shellenv)"
 
-  export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/lib"
-  export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/opt/mysql-client/lib"
-  export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/opt/libssh2/lib/"
-  export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/Cellar/suite-sparse/7.10.1/lib/"
-  export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/mysql-client/include -I$HOMEBREW_PREFIX/opt/libssh2/include/ -I$HOMEBREW_PREFIX/Cellar/libssh2/1.11.1/include/"
-  export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/mysql-client/lib/pkgconfig"
-  # export PATH="$PATH:$HOMEBREW_PREFIX/opt/mysql-client/bin"
-  # export PATH="$PATH:$HOMEBREW_PREFIX/opt/openjdk/bin"
-  export PATH="$HOMEBREW_PREFIX/lib/ruby/gems/3.4.0/bin:$PATH"
-  export PATH="$HOMEBREW_PREFIX/bin:$PATH"
+	export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/lib"
+	export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/opt/mysql-client/lib"
+	export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/opt/libssh2/lib/"
+	export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/Cellar/suite-sparse/7.10.1/lib/"
+	export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/mysql-client/include -I$HOMEBREW_PREFIX/opt/libssh2/include/ -I$HOMEBREW_PREFIX/Cellar/libssh2/1.11.1/include/"
+	export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/mysql-client/lib/pkgconfig"
+	export PATH="$HOMEBREW_PREFIX/lib/ruby/gems/3.4.0/bin:$PATH"
+	export PATH="$HOMEBREW_PREFIX/bin:$PATH"
 
-  [[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
+	[[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
 fi
 
 # User specific environment
 export PATH="$HOME/.local/bin:$HOME/bin:$PATH"
 
-# fuck
-# eval "$(thefuck --alias)"
 
 # history
 shopt -s histappend
@@ -73,12 +69,12 @@ export EDITOR="vim -u ~/.config/nvim/editor.lua"
 
 # GO
 if [ -f "$HOME/.gvm/scripts/gvm" ]; then
-  source "$HOME/.gvm/scripts/gvm"
+	source "$HOME/.gvm/scripts/gvm"
 fi
 
 if command -v go &>/dev/null; then
-  GOPATH=$(go env GOPATH)
-  export PATH=$PATH:$GOPATH/bin
+	GOPATH=$(go env GOPATH)
+	export PATH=$PATH:$GOPATH/bin
 fi
 
 # Android
@@ -90,103 +86,87 @@ export PATH=$PATH:$HOME/.cargo/bin
 
 # git
 if [ -f /usr/share/git/completion/git-completion.bash ]; then
-  source /usr/share/git/completion/git-completion.bash
-  source /usr/share/git/completion/git-prompt.sh
+	source /usr/share/git/completion/git-completion.bash
+	source /usr/share/git/completion/git-prompt.sh
 fi
 
 if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
-  source /usr/share/git-core/contrib/completion/git-prompt.sh
+	source /usr/share/git-core/contrib/completion/git-prompt.sh
 fi
 
 if [ -f /etc/bash_completion.d/git-prompt ]; then
-  source /etc/bash_completion.d/git-prompt
+	source /etc/bash_completion.d/git-prompt
 fi
 
 # Only load starship in interactive shells, not from a script or from scp
 [[ $- == *i* ]] && eval "$(starship init bash)"
 
 # gitignore.io
-function gi() { curl -L -s "https://www.gitignore.io/api/${*}"; }
+function gi() { curl -fL -s "https://www.gitignore.io/api/${*}" || echo "Error: Failed to fetch gitignore template"; }
 
 # NVM
 export NVM_DIR="$([ "${XDG_CONFIG_HOME-}" = "" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
 export NODE_VERSION_PREFIX=v
 export NODE_VERSIONS="${NVM_DIR}/versions/node"
 if [ -d "$NVM_DIR" ]; then
-  export NVM_DIR="$HOME/.config/nvm"
-  export NVM_SYMLINK_CURRENT=true
-  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
-  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
-  cdnvm() {
-    command cd "$@" || exit
-    nvm_path=$(nvm_find_up .nvmrc | tr -d '\n')
+	export NVM_SYMLINK_CURRENT=true
+	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
+	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
+	cdnvm() {
+		command cd "$@" || exit
+		nvm_path=$(nvm_find_up .nvmrc | tr -d '\n')
 
-    # If there are no .nvmrc file, use the default nvm version
-    if [[ $nvm_path != *[^[:space:]]* ]]; then
+		# If there are no .nvmrc file, use the default nvm version
+		if [[ $nvm_path != *[^[:space:]]* ]]; then
 
-      declare default_version
-      default_version=$(nvm version default)
+			declare default_version
+			default_version=$(nvm version default)
 
-      # If there is no default version, set it to `node`
-      # This will use the latest version on your machine
-      if [[ $default_version == "N/A" ]]; then
-        nvm alias default node
-        default_version=$(nvm version default)
-      fi
+			# If there is no default version, set it to `node`
+			# This will use the latest version on your machine
+			if [[ $default_version == "N/A" ]]; then
+				nvm alias default node
+				default_version=$(nvm version default)
+			fi
 
-      # If the current version is not the default version, set it to use the default version
-      if [[ $(nvm current) != "$default_version" ]]; then
-        nvm use default
-      fi
+			# If the current version is not the default version, set it to use the default version
+			if [[ $(nvm current) != "$default_version" ]]; then
+				nvm use default
+			fi
 
-    elif [[ -s $nvm_path/.nvmrc && -r $nvm_path/.nvmrc ]]; then
-      declare nvm_version
-      nvm_version=$(<"$nvm_path"/.nvmrc)
+		elif [[ -s $nvm_path/.nvmrc && -r $nvm_path/.nvmrc ]]; then
+			declare nvm_version
+			nvm_version=$(<"$nvm_path"/.nvmrc)
 
-      declare locally_resolved_nvm_version
-      # `nvm ls` will check all locally-available versions
-      # If there are multiple matching versions, take the latest one
-      # Remove the `->` and `*` characters and spaces
-      # `locally_resolved_nvm_version` will be `N/A` if no local versions are found
-      locally_resolved_nvm_version=$(nvm ls --no-colors "$nvm_version" | tail -1 | tr -d '\->*' | tr -d '[:space:]')
+			declare locally_resolved_nvm_version
+			# `nvm ls` will check all locally-available versions
+			# If there are multiple matching versions, take the latest one
+			# Remove the `->` and `*` characters and spaces
+			# `locally_resolved_nvm_version` will be `N/A` if no local versions are found
+			locally_resolved_nvm_version=$(nvm ls --no-colors "$nvm_version" | tail -1 | tr -d '\->*' | tr -d '[:space:]')
 
-      # If it is not already installed, install it
-      # `nvm install` will implicitly use the newly-installed version
-      if [[ $locally_resolved_nvm_version == "N/A" ]]; then
-        nvm install "$nvm_version"
-      elif [[ $(nvm current) != "$locally_resolved_nvm_version" ]]; then
-        nvm use "$nvm_version"
-      fi
-    fi
-  }
-  alias cd='cdnvm'
-  cd "$PWD" || exit
-  export PATH="$PATH:$NVM_DIR/current/bin"
+			# If it is not already installed, install it
+			# `nvm install` will implicitly use the newly-installed version
+			if [[ $locally_resolved_nvm_version == "N/A" ]]; then
+				nvm install "$nvm_version"
+			elif [[ $(nvm current) != "$locally_resolved_nvm_version" ]]; then
+				nvm use "$nvm_version"
+			fi
+		fi
+	}
+	alias cd='cdnvm'
+	cd "$PWD" || exit
+	export PATH="$PATH:$NVM_DIR/current/bin"
 fi
 
 # python {
 # export PIPENV_VENV_IN_PROJECT=1
 export PYTHONDONTWRITEBYTECODE=1
 
-# # pyenv
-# export PYENV_ROOT="$HOME/.pyenv"
-# export PYENV_VIRTUALENV_VERBOSE_ACTIVATE=true
-# export PYTHON_CONFIGURE_OPTS="--enable-shared --with-tcltk-includes --with-tcltk-libs"
-# export PATH="$HOME/.pyenv/bin:$PATH"
-# if command -v pyenv 1>/dev/null 2>&1; then
-# 	eval "$(pyenv init -)"
-# 	eval "$(pyenv init --path)"
-# 	eval "$(pyenv virtualenv-init -)"
-#
-# 	if pyenv which inv &>/dev/null; then
-# 		source <(inv --print-completion-script bash)
-# 	fi
-#
-# fi
 
 # AWS
 if command -v aws &>/dev/null; then
-  complete -C "$(which aws_completer)" aws
+	complete -C "$(command -v aws_completer)" aws
 fi
 
 # Alias definitions.
@@ -195,16 +175,16 @@ fi
 # See /usr/share/doc/bash-doc/examples in the bash-doc package.
 
 if [ -f ~/.bash_aliases ]; then
-  . ~/.bash_aliases
+	. ~/.bash_aliases
 fi
 
 # enable programmable completion features (you don't need to enable
 # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
 # sources /etc/bash.bashrc).
 if [ -f /usr/share/bash-completion/bash_completion ]; then
-  source /usr/share/bash-completion/bash_completion
+	source /usr/share/bash-completion/bash_completion
 elif [ -f /etc/bash_completion ]; then
-  source /etc/bash_completion
+	source /etc/bash_completion
 fi
 
 # FZF
@@ -220,14 +200,14 @@ export FZF_DEFAULT_COMMAND='ag --follow --nocolor --filename-pattern "" --hidden
 export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
 
 if command -v batcat &>/dev/null; then
-  export FZF_CTRL_T_OPTS="--preview-window 'right:60%' --layout reverse --margin=1,4 --preview 'batcat --theme='Nord' --color=always --style=header,grid --line-range :300 {}'  "
+	export FZF_CTRL_T_OPTS="--preview-window 'right:60%' --layout reverse --margin=1,4 --preview 'batcat --theme='Nord' --color=always --style=header,grid --line-range :300 {}'  "
 else
-  export FZF_CTRL_T_OPTS="--preview-window 'right:60%' --layout reverse --margin=1,4 --preview 'bat --theme='Nord' --color=always --style=header,grid --line-range :300 {}'  "
+	export FZF_CTRL_T_OPTS="--preview-window 'right:60%' --layout reverse --margin=1,4 --preview 'bat --theme='Nord' --color=always --style=header,grid --line-range :300 {}'  "
 fi
 
 # set variable identifying the chroot you work in (used in the prompt below)
 if [ "${debian_chroot:-}" = "" ] && [ -r /etc/debian_chroot ]; then
-  debian_chroot=$(cat /etc/debian_chroot)
+	debian_chroot=$(cat /etc/debian_chroot)
 fi
 
 # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
@@ -238,35 +218,28 @@ export NODE_OPTIONS="--max_old_space_size=16384 "
 export NODE_NO_WARNINGS=1
 
 if command -v npm &>/dev/null; then
-  source <(npm completion)
+	source <(npm completion)
 fi
 
 if command -v direnv &>/dev/null; then
-  eval "$(direnv hook bash)"
+	eval "$(direnv hook bash)"
 fi
 
 # https://cloud.google.com/sdk/gcloud/reference/topic/startup
 export CLOUDSDK_PYTHON=python3
 
-# source "$HOME/bin/emsdk/emsdk_env.sh" 2>/dev/null
 if [ -f "${HOME}/.dir_colors" ]; then
-  eval "$(dircolors ~/.dir_colors)"
+	eval "$(dircolors ~/.dir_colors)"
 fi
 
 if [ -f "${HOME}/.config/broot/launcher/bash/br" ]; then
-  source "${HOME}/.config/broot/launcher/bash/br"
-fi
-
-if [ -f "$HOME/.cargo/env" ]; then
-  source "$HOME/.cargo/env"
+	source "${HOME}/.config/broot/launcher/bash/br"
 fi
 
 if [ -d "${HOME}/dotfiles" ]; then
-  # Your dotdrop git repository location
-  export DOTREPO="$HOME/dotfiles"
-  source "${DOTREPO}/dotdrop/completion/dotdrop-completion.bash"
-else
-  echo "NO DOTFILES ${HOME}/dotfiles"
+	# Your dotdrop git repository location
+	export DOTREPO="$HOME/dotfiles"
+	source "${DOTREPO}/dotdrop/completion/dotdrop-completion.bash"
 fi
 
 # https://ask.fedoraproject.org/t/intel-graphics-best-practices-and-settings-for-hardware-acceleration/21119
@@ -274,7 +247,7 @@ fi
 export LIBVA_DRIVER_NAME=iHD
 
 if command -v helm &>/dev/null; then
-  source <(helm completion bash)
+	source <(helm completion bash)
 fi
 
 . "$HOME/.cargo/env"
@@ -283,27 +256,27 @@ export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
 
 # The next line updates PATH for the Google Cloud SDK.
 if [ -f "$HOME/bin/google-cloud-sdk/path.bash.inc" ]; then
-  source "$HOME/bin/google-cloud-sdk/path.bash.inc"
+	source "$HOME/bin/google-cloud-sdk/path.bash.inc"
 fi
 
 # The next line enables shell command completion for gcloud.
 if [ -f "$HOME/bin/google-cloud-sdk/completion.bash.inc" ]; then
-  source "$HOME/bin/google-cloud-sdk/completion.bash.inc"
+	source "$HOME/bin/google-cloud-sdk/completion.bash.inc"
 fi
 
 if command -v kubectl &>/dev/null; then
-  source <(kubectl completion bash)
+	source <(kubectl completion bash)
 fi
 
 if command -v k9s &>/dev/null; then
-  eval "$(k9s completion bash)"
+	eval "$(k9s completion bash)"
 fi
 
 export ERG_PATH="$HOME/.local/share/nvim/mason/packages/erg"
 export LUA_CPATH="$HOME/.luarocks/lib/lua/5.1/?.so;$HOME/.luarocks/lib/lua/5.1/loadall.so"
 
 # pnpm
-export PNPM_HOME="/Users/andres.monge/Library/pnpm"
+export PNPM_HOME="$HOME/Library/pnpm"
 case ":$PATH:" in
 *":$PNPM_HOME:"*) ;;
 *) export PATH="$PNPM_HOME:$PATH" ;;
@@ -311,8 +284,7 @@ esac
 
 export DOTDROP_VIRTUALENV="${HOME}/dotfiles/.venv"
 
-# export LD_LIBRARY_PATH=$HOMEBREW_PREFIX/lib/:/usr/local/lib:/usr/lib:$LD_LIBRARY_PATH
 
-source '/Users/andres.monge/.bash_completions/complexipy.sh'
+source "$HOME/.bash_completions/complexipy.sh"
 
 export PATH="$HOME/.claude/local:$PATH"
